name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests (if any)
      - name: Run tests
        run: |
          echo "Add your test commands here"

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t chatbot .

      # Step 6: Log in to Docker Hub (or any container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag chatbot ${{ secrets.DOCKER_HUB_USERNAME }}/chatbot:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/chatbot:latest

      # Step 8: Deploy to a cloud platform (e.g., AWS ECS, Heroku, etc.)
      - name: Deploy to Heroku
        run: |
          echo "Add your deployment commands here"